-- 1. Create Table `document_daily_stats`
CREATE TABLE IF NOT EXISTS public.document_daily_stats (
    id bigint generated by default as identity primary key,
    document_id bigint references public.documents(id) on delete cascade not null,
    date date not null default current_date,
    view_count integer default 0,
    download_count integer default 0,
    unique(document_id, date)
);

ALTER TABLE public.document_daily_stats ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.document_daily_stats TO anon;
GRANT ALL ON public.document_daily_stats TO authenticated;
GRANT ALL ON public.document_daily_stats TO service_role;

CREATE POLICY "Anyone can read daily stats" ON public.document_daily_stats FOR SELECT USING (true);

-- 2. Update RPC `increment_doc_stat`
CREATE OR REPLACE FUNCTION public.increment_doc_stat(doc_id bigint, stat_type text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF stat_type = 'view' THEN
    -- Update all-time stat
    INSERT INTO document_analytics (document_id, view_count, download_count, last_accessed)
    VALUES (doc_id, 1, 0, now())
    ON CONFLICT (document_id)
    DO UPDATE SET 
      view_count = COALESCE(document_analytics.view_count, 0) + 1, 
      last_accessed = now();
      
    -- Update daily stat
    INSERT INTO document_daily_stats (document_id, date, view_count)
    VALUES (doc_id, CURRENT_DATE, 1)
    ON CONFLICT (document_id, date)
    DO UPDATE SET view_count = COALESCE(document_daily_stats.view_count, 0) + 1;
      
  ELSIF stat_type = 'download' THEN
    -- Update all-time stat
    INSERT INTO document_analytics (document_id, view_count, download_count, last_accessed)
    VALUES (doc_id, 0, 1, now())
    ON CONFLICT (document_id)
    DO UPDATE SET 
      download_count = COALESCE(document_analytics.download_count, 0) + 1, 
      last_accessed = now();
      
    -- Update daily stat
    INSERT INTO document_daily_stats (document_id, date, download_count)
    VALUES (doc_id, CURRENT_DATE, 1)
    ON CONFLICT (document_id, date)
    DO UPDATE SET download_count = COALESCE(document_daily_stats.download_count, 0) + 1;
  END IF;
END;
$$;

-- 3. Create View `weekly_trending_documents`
CREATE OR REPLACE VIEW public.weekly_trending_documents AS
SELECT 
  d.id,
  d.title,
  d.category,
  d.file_url,
  d.uploaded_by,
  d.created_at,
  d.module_id,
  d.subject,
  d.status,
  d.file_size,
  d.page_count,
  d.thumbnail_url,
  d.uploader_name,
  d.fts,
  d.moderated_by,
  d.rejection_reason,
  d.updated_at,
  d.resubmission_count,
  COALESCE(SUM(dds.view_count), 0)::bigint AS weekly_views,
  da.view_count AS all_time_view_count,
  da.upvotes,
  da.downvotes
FROM documents d
JOIN document_daily_stats dds ON dds.document_id = d.id
LEFT JOIN document_analytics da ON da.document_id = d.id
WHERE d.status = 'approved' 
  AND dds.date >= CURRENT_DATE - INTERVAL '7 days'
GROUP BY 
  d.id, d.title, d.category, d.file_url, d.uploaded_by, d.created_at, 
  d.module_id, d.subject, d.status, d.file_size, d.page_count, 
  d.thumbnail_url, d.uploader_name, d.fts, d.moderated_by, 
  d.rejection_reason, d.updated_at, d.resubmission_count,
  da.view_count, da.upvotes, da.downvotes;

GRANT SELECT ON public.weekly_trending_documents TO anon, authenticated, service_role;
